### ISSUE TITLE
Windows Service support

### ISSUE THREAD

**Issue by mauricioQrails** [chrisism/VSTS.ApplyTransformations#5]
hi,

I am trying to use your fine code with a windows service config. yet  the log says:

**2018-02-27T20:56:51.0773593Z Applying release transforms to all config files in 
2018-02-27T20:56:51.0774039Z 
2018-02-27T20:56:51.0800016Z 
2018-02-27T20:56:51.0800320Z Found no files.**_**

**Comment by chrisism** [comment]
You have locked this issue yourself. Is the issue resolved?

**Comment by mauricioQrails** [comment]
Thank you for replying. I found a work around.

The issue is that if you try doing the transform during a release of a windows service the original config files are not there. I ended up using a different task which allowed me to enter a path where to find the source config.  Hence on my release I added the source code as an artifact which allowed me to give that path to the other Task.
